### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by jacktian-web** [james-e-morris/hx711-multi#4]
![image](https://user-images.githubusercontent.com/73347373/127995392-5924fb64-cb89-4225-8465-75fa12199f77.png)
There are a lot of errors same like this.

**Comment by james-e-morris** [comment]
What version of Python are you using? This was developed and tested in Python 3.8. That error is pointing at a variable type definition which was introduced in Python 3.5

**Comment by james-e-morris** [comment]
Closing this as @jacktian-web commented elsewhere that he is switching to a different chip as this one doesn't sample fast enough for his needs
