### ISSUE TITLE
Error in basic usage example

### ISSUE THREAD

**Issue by TadeuClemente** [james-e-morris/hx711-multi#5]
Hi, Morris. I'm the guy from the gandalf post.

I installed the HX711_multi library and tried to run the basic code.

This time the library was recognized but failed to zero the load cells. I don't quite understand if I have to change some value before running the code.

![Teste 3 - Erro ao zerar SG](https://user-images.githubusercontent.com/89172087/131911461-f624209e-3717-43ee-a813-e6f1bfe8dbdd.png)

**Comment by james-e-morris** [comment]
@TadeuClemente it looks like the readings for the zero operation all failed to read. This means either the HX711 isn't wired or configured properly, or the signal is noisy or something. Have you configured the GPIO Pin and SCK pin to match your input and clock pin? Please share your code.

**Comment by TadeuClemente** [comment]
I only want to take raw data from HX711 (strain variations for deformation analysis), then i used the code you shared for basic usage in your post about "HX711_multi". I did some changes in the code, changing the first Dout_pin to 5 and Sck_pin to 6. The VCC pin is in 3.3V.

I have another question about the "src.HX711 multi" module. When I run the code, the "src" module is not recognized.

![image](https://user-images.githubusercontent.com/89172087/132102865-4cb966ab-46d8-4be4-bdbd-1e114833758b.png)

**Comment by james-e-morris** [comment]
@TadeuClemente go ahead and remove the extra dout pins from the list (short for digital out) and set the multiple to 1, so you should only have:
```
dout_pins = [5]
sck_pin = 6
weight_multiples = [1]
```

`all_or_nothing` is set to False, so you shouldn't need to worry about extra dout pins, but perhaps that is part of the issue if those pins are floating.

Regarding the src.hx77_multi: that is part of the example script if you are running it locally next to the src code. Otherwise, as you have in your screenshot correctly, you should import hx711_multi just like any other package.

**Comment by TadeuClemente** [comment]
![Teste 5 - Erro dout pin](https://user-images.githubusercontent.com/89172087/132912764-5d0b74e0-8eaf-4a0a-a1ba-9c84ee646540.png)

Removing the extra pins the code flowed, but in a loop always returning the same value for 'wt' and sometimes for 'raw'.
In a second test the error was different, as shown in the screenshot.

In the first test I inserted approximately 700 grams before running the code. In the second test, weighted or not, it returns the same error.

I apologize for so many doubts, but my deadline is running out and I need to finish this part of the project.

**Comment by james-e-morris** [comment]
It seems to me like there's an issue with your hardware and you aren't receiving back measurements with enough frequency to accurately zero your scale, or you're only reading a single measurement and expecting it to always be a valid read. What value are you using for `readings_to_average` when you zero and when you read? What part of your code is printing these `raw` and `wt` values? I'm interested in how you got "-0.130" because I believe that would require you to set a `multiple` value higher than 1. The measurements you get out raw should be integers.

In my example I use 30 samples to zero to ensure enough samples are valid for the zero value. I then read 10 samples for each read operation to ensure I get a few valid samples per read.

With my ADCs, I found that the readings are often bad, so you need to pull many samples to get good data. If you use the `lc.reads` print I mentioned in the last thread (and below), you should see all 30 or 10 samples that you just read so you can see how dirty the data is. 

---

I'm going to copy the code I shared on the other repo here for reference:
If you want the really really raw data, you can access that within the load_cell data after performing the read above:
```python
for lc in hx711._load_cells:
    print(lc.raw_reads) # these are the 2's complemented values read bitwise from the hx711
    print(lc.reads) # these are the raw values after being converted to signed integers
```

**Comment by TadeuClemente** [comment]
I haven't changed anything other than what you recommended earlier.

![Código ](https://user-images.githubusercontent.com/89172087/132925704-bf728f65-5490-4747-990f-258f96bc9e5e.png)


Average values ​​are:

#reset ADC, zero it
hx711.reset()
hx711.zero(readings_to_average=30)
hx711.set_weight_multiples(weight_multiples=weight_multiples)

and,

raw_vals = hx711.read_raw(readings_to_average=10)

**Comment by james-e-morris** [comment]
What is printed when you add the deep level raw data prints that I mentioned above? Added print statements:
```python
try:
    while True:
        start = perf_counter()
        raw_vals = hx711.read_raw(readings_to_average=10)
        weights = hx711.read_weight(use_prev_read=True)
        read_duration = perf_counter() - start
        print('\nread duration: {:.3f} seconds'.format(read_duration))
        print('raw', ['{:.3f}'.format(x) if x is not None else None for x in raw_vals])
        print(' wt', ['{:.3f}'.format(x) if x is not None else None for x in weights])
        for lc in hx711._load_cells:
            print(lc.raw_reads) # these are the 2's complemented values read bitwise from the hx711
            print(lc.reads) # these are the raw values after being converted to signed integers
except KeyboardInterrupt:
    print('Keyboard interrupt..')
except Exception as e:
    print(e)
```

FYI, you can share code on here by using three of the little funny-apostrophes (grave accent) at the top right of your keyboard:
\```
[code]
\```

**Comment by TadeuClemente** [comment]
The same error appears when I add the deep level raw data.
At this point I had inserted 900g into the structure before running the code

![Teste (ignore)](https://user-images.githubusercontent.com/89172087/132927089-57720f12-b2aa-46bb-9bee-49a9b7ba404e.png)

Here's the complete code.

```
#!/usr/bin/env python3

from hx711_multi import HX711
from time import perf_counter
import RPi.GPIO as GPIO  # import GPIO

#init GPIO (should be done outside HX711 module in case you are using other GPIO functionality)
GPIO.setmode(GPIO.BCM)  # set GPIO pin mode to BCM numbering

dout_pins = [5]
sck_pin = 6
weight_multiples = [1]

hx711 = HX711(dout_pins=dout_pins, sck_pin=sck_pin, all_or_nothing=False, log_level='CRITICAL')  # create an object
hx711.reset()
hx711.zero()
hx711.set_weight_multiples(weight_multiples=weight_multiples)

# read until keyboard interrupt
try:
    while True:
        start = perf_counter()
        raw_vals = hx711.read_raw(readings_to_average=10)
        weights = hx711.read_weight(use_prev_read=True)
        read_duration = perf_counter() - start
        print('\nread duration: {:.3f} seconds'.format(read_duration))
        print('raw', ['{:.3f}'.format(x) if x is not None else None for x in raw_vals])
        print(' wt', ['{:.3f}'.format(x) if x is not None else None for x in weights])
        for lc in hx711._load_cells:
            print(lc.raw_reads) # these are the 2's complemented values read bitwise from the hx711
            print(lc.reads) # these are the raw values after being converted to signed integers
except KeyboardInterrupt:
    print('Keyboard interrupt..')
except Exception as e:
    print(e)

# cleanup GPIO
GPIO.cleanup()
```

**Comment by james-e-morris** [comment]
Please try to run your code with no weight on the structure and make sure that it is on a flat surface and isn't moving/vibrating. These sensors are very sensitive to noise and will not be able to zero if there is a lot of noise. Potentially, we will need to open up our noise filtering thresholds in your case? Try to run over and over until you get past the zeroing and read at least one datapoint like you did earlier.

Please also confirm your hardware is configured as expected. The default in my code is Channel A and configured with a gain of 128. You can [view the PDF provided in the docs folder](https://github.com/Morrious/hx711-multi/blob/prod/docs/hx711.pdf) to see how the HX711 channel wiring works.

**Comment by TadeuClemente** [comment]
I did as you recommended and the most common failures were:
![Teste 7 - Erro ao zerar e peso 0](https://user-images.githubusercontent.com/89172087/132953463-825264b1-bdf9-4f5d-bbde-23e13eb7cb84.png)

I don't understand why couldn't zero the load cells, Cable connections are right, as you can see here:
![WhatsApp Image 2021-09-11 at 12 44 27](https://user-images.githubusercontent.com/89172087/132953635-5f3b73f4-2900-4583-8fef-9f17ec07b147.jpeg)

Should I insert an external power supply into the E+ input? Because I'm only using 3.3V from raspberry in VCC input.

**Comment by james-e-morris** [comment]
Personally, we use 5V, so I would try that next. That shouldn't be necessary per the HX711 specs, but maybe it will help. [You Pi has a 5V output as well](https://www.etechnophiles.com/raspberry-pi-zero-gpio-pinout-specifications-programming-language/), it's just the pin right above your orange wire in your picture.

Ours are wired similarly:
![PXL_20210724_220811806](https://user-images.githubusercontent.com/32372811/132954341-f2fffcdc-c96d-443c-ad46-29b5d5718506.jpg)

**Comment by TadeuClemente** [comment]
The error still remains with 5V. 

I removed all pins E + E- A + and A- and ran the code. The same error appeared (Failed to zero load cells).  I'm almost giving up

**Comment by james-e-morris** [comment]
Can you verify your clock pin in triggering properly? Put a voltmeter on that output from your Pi and confirm you can set it high and low at command. I'm not sure what else to check, other than manually triggering your HX711 to make sure the inputs and outputs are what you expect.Verify the power the board is there, plus the clock is triggering. Wire the clock pin directly to your input pin and confirm you can read back what you write out, that sort of thing.

**Comment by james-e-morris** [comment]
You may be able to still read the raw values from the zeroing read operation if you ignore the error when zeroing. Try the below code and let's see what the deep 2's complement values are that you're getting from your ADC:

```python
try:
    hx711.zero(readings_to_average=30)
except: pass
print(vars(hx711._load_cells[0])) # this will print the entire first load cell object (note: latest version of hx711-multi renamed this attribute to "_adcs"

**Comment by james-e-morris** [comment]
Closing this for now as I haven't heard back in a while. Based on other users not experiencing this issue and my own codeset still functioning, I expect this to be a hardware issue.

Please re-open if there's more help I can provide.
